---

  - name: Include file for {{ansible_distribution}} {{ansible_distribution_major_version}}
    include: "{{ansible_distribution | lower}}_{{ansible_distribution_major_version}}.yml"
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: Include file for {{ansible_distribution}} {{ansible_distribution_major_version}}
    include: "{{ansible_distribution | lower}}.yml"
    when: ansible_distribution == 'MacOSX'
