---
- set_fact:
    ssh_key_id: {{ jumpcloud_user.json.results.0.ssh_keys.0.id }}
    when: ssh_key_id is undefined

- name: Remove an SSH Key from JumpCloud
  uri:
    headers:
      x-api-key: "{{ jumpcloud_api_key | mandatory }}"
    method: DELETE
    url: "{{ ssh_endpoint }}/{{ ssh_key_id }}"
