---

- name: Get User by ID
  include: get_user.yml

- name: Prepare local storage
  include: local_storage.yml
  when: delete_key is undefined

- name: Generate SSH keys
  include: generate_keys.yml
  when: delete_key is undefined

- name: Append user's SSH key to JumpCloud
  include: add_keys_jc.yml
  when: delete_key is undefined

- name: Remove SSH Key from JumpCloud
  include: delete_keys_jc.yml
  when: delete_key is defined

- name: Write SSH Key to Vault
  include: add_keys_vault.yml
  when: delete_key is undefined
