---

- name: Get user id by username
  uri:
    headers:
      x-api-key: "{{ jumpcloud_api_key | mandatory }}"
    method: POST
    url: "{{ jumpcloud_searchusers_endpoint }}"
    body_format: json
    body:
      filter: [username: "{{ jumpcloud_username }}"]
  register: jumpcloud_user

- file:
    path: "{{ ansible_env.HOME }}/sshkeys"
    state: directory

- set_fact:
    ssh_directory: "{{ ansible_env.HOME }}/sshkeys"

- name: Remove existing SSH Key "{{ jumpcloud_username }}_rsa" if found
  file:
    path: "{{ssh_directory}}/{{ item }}"
    state: absent
  with_items:
    - "{{ jumpcloud_username }}_rsa"
    - "{{ jumpcloud_username }}_rsa.pub"

- name: Generate SSH keys for {{ jumpcloud_username }}
  command: ssh-keygen -q -t rsa -b 4096 -C "{{ jumpcloud_username }}{{ domain }}" -f "{{ jumpcloud_username }}_rsa" -N ""
  args:
    chdir: "{{ ssh_directory }}"

- set_fact:
    ssh_private: "{{ ssh_directory }}/{{ jumpcloud_username }}_rsa"
    ssh_public: "{{ ssh_directory }}/{{ jumpcloud_username }}_rsa.pub"
- set_fact:
    ssh_private_key: "{{ lookup('file', ssh_private )}}"
    ssh_public_key: "{{ lookup('file', ssh_public )}}"
    ssh_endpoint: "{{ jumpcloud_systemusers_endpoint }}/{{ jumpcloud_user.json.results.0._id }}/sshkeys"

- name: Append user's SSH key to JumpCloud
  uri:
    headers:
      x-api-key: "{{ jumpcloud_api_key | mandatory }}"
    method: POST
    url: "{{ ssh_endpoint }}"
    body_format: json
    body: "{{ lookup('template','body.j2') }}"

- name: Check Vault status
  uri:
    headers:
      X-Vault-Token: "{{ vault_token }}"
    method: GET
    url: "{{ vault_health_endpoint }}"
    status_code: 200
    register: vaultStatus
    when: vault is defined

- name: Write SSH key to Vault
  uri:
    headers:
      X-Vault-Token: "{{ vault_token }}"
      Content-Type: 'application/json'
    method: POST
    url: "{{ vault_secret_endpoint }}/{{ jumpcloud_username }}"
    body_format: json
    body:
      private_key: "{{ ssh_private_key }}"
      public_key: "{{ ssh_public_key }}"
    status_code: "200,204"
